name: Process and Resize Photos

on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.9'

      - name: Install dependencies
        run: pip install Pillow

      - name: Run script
        run: python process_photos.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Refresh photos.json and optimize images" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
